/* Paris Métro game data — curated, high-confidence subset.
   Network state: as of mid-2024 (line 11 extension to Rosny–Bois-Perrier,
   line 14 extension to Saint-Denis–Pleyel / Aéroport d'Orly, line 4 to Bagneux).
   Grand Paris Express lines 15–18 are deliberately excluded. */

const LINES = {
  "1":    { color: "#FFCE00", ink: "#000", termini: ["La Défense", "Château de Vincennes"], count: 25 },
  "2":    { color: "#0064B0", ink: "#fff", termini: ["Porte Dauphine", "Nation"], count: 25 },
  "3":    { color: "#9F9825", ink: "#fff", termini: ["Pont de Levallois–Bécon", "Gallieni"], count: 25 },
  "3bis": { color: "#99D4DE", ink: "#000", termini: ["Gambetta", "Porte des Lilas"], count: 4 },
  "4":    { color: "#C04191", ink: "#fff", termini: ["Porte de Clignancourt", "Bagneux–Lucie Aubrac"], count: 29 },
  "5":    { color: "#F28E42", ink: "#000", termini: ["Bobigny–Pablo Picasso", "Place d'Italie"], count: 22 },
  "6":    { color: "#83C491", ink: "#000", termini: ["Charles de Gaulle–Étoile", "Nation"], count: 28 },
  "7":    { color: "#F3A4BA", ink: "#000", termini: ["La Courneuve–8 Mai 1945", "Villejuif–Louis Aragon", "Mairie d'Ivry"], count: 38 },
  "7bis": { color: "#83C491", ink: "#000", termini: ["Louis Blanc", "Pré-Saint-Gervais"], count: 8 },
  "8":    { color: "#CEADD2", ink: "#000", termini: ["Balard", "Pointe du Lac"], count: 38 },
  "9":    { color: "#D5C900", ink: "#000", termini: ["Pont de Sèvres", "Mairie de Montreuil"], count: 37 },
  "10":   { color: "#E3B32A", ink: "#000", termini: ["Boulogne–Pont de Saint-Cloud", "Gare d'Austerlitz"], count: 23 },
  "11":   { color: "#8D5E2A", ink: "#fff", termini: ["Châtelet", "Rosny–Bois-Perrier"], count: 19 },
  "12":   { color: "#007852", ink: "#fff", termini: ["Aubervilliers–Front Populaire", "Mairie d'Issy"], count: 29 },
  "13":   { color: "#6EC4E8", ink: "#000", termini: ["Châtillon–Montrouge", "Saint-Denis–Université", "Asnières–Gennevilliers Les Courtilles"], count: 32 },
  "14":   { color: "#62259D", ink: "#fff", termini: ["Saint-Denis–Pleyel", "Aéroport d'Orly"], count: 21 }
};

const LINE_IDS = Object.keys(LINES);

/* station name -> lines serving it (métro only; RER connections omitted) */
const STATIONS = {
  // ——— Line 1
  "La Défense": ["1"], "Esplanade de la Défense": ["1"], "Pont de Neuilly": ["1"],
  "Les Sablons": ["1"], "Porte Maillot": ["1"], "Argentine": ["1"],
  "George V": ["1"], "Champs-Élysées–Clemenceau": ["1", "13"],
  "Tuileries": ["1"], "Louvre–Rivoli": ["1"], "Saint-Paul": ["1"],
  "Porte de Vincennes": ["1"], "Saint-Mandé": ["1"], "Bérault": ["1"],
  "Château de Vincennes": ["1"],
  // ——— Line 2
  "Porte Dauphine": ["2"], "Victor Hugo": ["2"], "Ternes": ["2"], "Courcelles": ["2"],
  "Monceau": ["2"], "Rome": ["2"], "Blanche": ["2"], "Anvers": ["2"],
  "La Chapelle": ["2"], "Colonel Fabien": ["2"], "Couronnes": ["2"],
  "Ménilmontant": ["2"], "Philippe Auguste": ["2"], "Alexandre Dumas": ["2"], "Avron": ["2"],
  // ——— Line 3
  "Pont de Levallois–Bécon": ["3"], "Anatole France": ["3"], "Louise Michel": ["3"],
  "Porte de Champerret": ["3"], "Pereire": ["3"], "Wagram": ["3"], "Malesherbes": ["3"],
  "Europe": ["3"], "Quatre-Septembre": ["3"], "Bourse": ["3"], "Sentier": ["3"],
  "Temple": ["3"], "Parmentier": ["3"], "Rue Saint-Maur": ["3"],
  "Porte de Bagnolet": ["3"], "Gallieni": ["3"],
  // ——— Line 3bis
  "Pelleport": ["3bis"], "Saint-Fargeau": ["3bis"],
  // ——— Line 4
  "Porte de Clignancourt": ["4"], "Simplon": ["4"], "Château Rouge": ["4"],
  "Château d'Eau": ["4"], "Étienne Marcel": ["4"], "Les Halles": ["4"], "Cité": ["4"],
  "Saint-Michel": ["4"], "Saint-Germain-des-Prés": ["4"], "Saint-Sulpice": ["4"],
  "Saint-Placide": ["4"], "Vavin": ["4"], "Mouton-Duvernet": ["4"], "Alésia": ["4"],
  "Porte d'Orléans": ["4"], "Mairie de Montrouge": ["4"], "Barbara": ["4"],
  "Bagneux–Lucie Aubrac": ["4"],
  // ——— Line 5
  "Bobigny–Pablo Picasso": ["5"], "Bobigny–Pantin Raymond Queneau": ["5"],
  "Hoche": ["5"], "Porte de Pantin": ["5"], "Ourcq": ["5"], "Laumière": ["5"],
  "Jacques Bonsergent": ["5"], "Quai de la Rapée": ["5"], "Saint-Marcel": ["5"],
  "Campo-Formio": ["5"],
  // ——— Line 6
  "Kléber": ["6"], "Boissière": ["6"], "Passy": ["6"], "Bir-Hakeim": ["6"],
  "Dupleix": ["6"], "Cambronne": ["6"], "Sèvres–Lecourbe": ["6"], "Edgar Quinet": ["6"],
  "Saint-Jacques": ["6"], "Glacière": ["6"], "Corvisart": ["6"], "Nationale": ["6"],
  "Chevaleret": ["6"], "Quai de la Gare": ["6"], "Dugommier": ["6"], "Bel-Air": ["6"], "Picpus": ["6"],
  // ——— Line 7
  "La Courneuve–8 Mai 1945": ["7"], "Fort d'Aubervilliers": ["7"],
  "Aubervilliers–Pantin Quatre Chemins": ["7"], "Porte de la Villette": ["7"],
  "Corentin Cariou": ["7"], "Crimée": ["7"], "Riquet": ["7"], "Château Landon": ["7"],
  "Poissonnière": ["7"], "Cadet": ["7"], "Le Peletier": ["7"], "Pyramides": ["7", "14"],
  "Pont Neuf": ["7"], "Pont Marie": ["7"], "Sully–Morland": ["7"],
  "Place Monge": ["7"], "Censier–Daubenton": ["7"], "Les Gobelins": ["7"],
  "Tolbiac": ["7"], "Le Kremlin-Bicêtre": ["7"], "Villejuif–Léo Lagrange": ["7"],
  "Villejuif–Paul Vaillant-Couturier": ["7"], "Villejuif–Louis Aragon": ["7"],
  "Pierre et Marie Curie": ["7"], "Mairie d'Ivry": ["7"],
  // ——— Line 7bis
  "Bolivar": ["7bis"], "Buttes Chaumont": ["7bis"], "Botzaris": ["7bis"],
  "Danube": ["7bis"], "Pré-Saint-Gervais": ["7bis"],
  // ——— Line 8
  "Balard": ["8"], "Lourmel": ["8"], "Boucicaut": ["8"], "Félix Faure": ["8"],
  "Commerce": ["8"], "École Militaire": ["8"], "La Tour-Maubourg": ["8"],
  "Ledru-Rollin": ["8"], "Faidherbe–Chaligny": ["8"], "Montgallet": ["8"],
  "Michel Bizot": ["8"], "Porte Dorée": ["8"], "Porte de Charenton": ["8"],
  "Liberté": ["8"], "Charenton–Écoles": ["8"], "Maisons-Alfort–Stade": ["8"],
  "Créteil–L'Échat": ["8"], "Créteil–Université": ["8"], "Créteil–Préfecture": ["8"],
  "Pointe du Lac": ["8"], "Saint-Sébastien–Froissart": ["8"], "Chemin Vert": ["8"],
  "Filles du Calvaire": ["8"],
  // ——— Line 9
  "Pont de Sèvres": ["9"], "Billancourt": ["9"], "Marcel Sembat": ["9"],
  "Porte de Saint-Cloud": ["9"], "Exelmans": ["9"], "Michel-Ange–Molitor": ["9", "10"],
  "Jasmin": ["9"], "Ranelagh": ["9"], "La Muette": ["9"], "Rue de la Pompe": ["9"],
  "Iéna": ["9"], "Alma–Marceau": ["9"], "Saint-Philippe du Roule": ["9"],
  "Saint-Augustin": ["9"], "Saint-Ambroise": ["9"], "Voltaire": ["9"],
  "Charonne": ["9"], "Rue des Boulets": ["9"], "Buzenval": ["9"], "Maraîchers": ["9"],
  "Porte de Montreuil": ["9"], "Robespierre": ["9"], "Croix de Chavaux": ["9"],
  "Mairie de Montreuil": ["9"],
  // ——— Line 10
  "Boulogne–Pont de Saint-Cloud": ["10"], "Porte d'Auteuil": ["10"],
  "Michel-Ange–Auteuil": ["9", "10"], "Église d'Auteuil": ["10"],
  "Javel–André Citroën": ["10"], "Charles Michels": ["10"], "Avenue Émile Zola": ["10"],
  "Ségur": ["10"], "Vaneau": ["10"], "Mabillon": ["10"], "Cluny–La Sorbonne": ["10"],
  "Maubert–Mutualité": ["10"], "Cardinal Lemoine": ["10"],
  // ——— Line 11
  "Rambuteau": ["11"], "Goncourt": ["11"], "Pyrénées": ["11"], "Jourdain": ["11"],
  "Télégraphe": ["11"], "Mairie des Lilas": ["11"], "Serge Gainsbourg": ["11"],
  "Romainville–Carnot": ["11"], "Rosny–Bois-Perrier": ["11"],
  // ——— Line 12
  "Aubervilliers–Front Populaire": ["12"], "Porte de la Chapelle": ["12"],
  "Marx Dormoy": ["12"], "Jules Joffrin": ["12"], "Lamarck–Caulaincourt": ["12"],
  "Abbesses": ["12"], "Saint-Georges": ["12"], "Notre-Dame-de-Lorette": ["12"],
  "Trinité–d'Estienne d'Orves": ["12"], "Assemblée Nationale": ["12"],
  "Solférino": ["12"], "Rue du Bac": ["12"], "Rennes": ["12"],
  "Notre-Dame-des-Champs": ["12"], "Falguière": ["12"], "Volontaires": ["12"],
  "Vaugirard": ["12"], "Convention": ["12"], "Porte de Versailles": ["12"],
  "Corentin Celton": ["12"], "Mairie d'Issy": ["12"],
  // ——— Line 13
  "Châtillon–Montrouge": ["13"], "Saint-François-Xavier": ["13"], "Varenne": ["13"],
  "Liège": ["13"], "La Fourche": ["13"], "Guy Môquet": ["13"],
  "Porte de Saint-Ouen": ["13"], "Basilique de Saint-Denis": ["13"],
  "Saint-Denis–Université": ["13"], "Brochant": ["13"], "Mairie de Clichy": ["13"],
  "Gabriel Péri": ["13"], "Les Agnettes": ["13"],
  "Asnières–Gennevilliers Les Courtilles": ["13"],
  // ——— Line 14
  "Saint-Denis–Pleyel": ["14"], "Mairie de Saint-Ouen": ["14"], "Pont Cardinet": ["14"],
  "Cour Saint-Émilion": ["14"], "Bibliothèque François Mitterrand": ["14"],
  "Olympiades": ["14"], "Hôpital Bicêtre": ["14"], "Villejuif–Gustave Roussy": ["14"],
  "L'Haÿ-les-Roses": ["14"], "Chevilly–Larue": ["14"], "Thiais–Orly": ["14"],
  "Aéroport d'Orly": ["14"],
  // ——— Interchanges
  "Châtelet": ["1", "4", "7", "11", "14"],
  "Hôtel de Ville": ["1", "11"],
  "Bastille": ["1", "5", "8"],
  "Gare de Lyon": ["1", "14"],
  "Reuilly–Diderot": ["1", "8"],
  "Nation": ["1", "2", "6", "9"],
  "Concorde": ["1", "8", "12"],
  "Palais Royal–Musée du Louvre": ["1", "7"],
  "Franklin D. Roosevelt": ["1", "9"],
  "Charles de Gaulle–Étoile": ["1", "2", "6"],
  "Place de Clichy": ["2", "13"],
  "Pigalle": ["2", "12"],
  "Barbès–Rochechouart": ["2", "4"],
  "Stalingrad": ["2", "5", "7"],
  "Jaurès": ["2", "5", "7bis"],
  "Belleville": ["2", "11"],
  "Père Lachaise": ["2", "3"],
  "Villiers": ["2", "3"],
  "Saint-Lazare": ["3", "12", "13", "14"],
  "Havre–Caumartin": ["3", "9"],
  "Opéra": ["3", "7", "8"],
  "Réaumur–Sébastopol": ["3", "4"],
  "Arts et Métiers": ["3", "11"],
  "République": ["3", "5", "8", "9", "11"],
  "Gambetta": ["3", "3bis"],
  "Porte des Lilas": ["3bis", "11"],
  "Gare du Nord": ["4", "5"],
  "Gare de l'Est": ["4", "5", "7"],
  "Marcadet–Poissonniers": ["4", "12"],
  "Strasbourg–Saint-Denis": ["4", "8", "9"],
  "Odéon": ["4", "10"],
  "Montparnasse–Bienvenüe": ["4", "6", "12", "13"],
  "Raspail": ["4", "6"],
  "Denfert-Rochereau": ["4", "6"],
  "Place d'Italie": ["5", "6", "7"],
  "Gare d'Austerlitz": ["5", "10"],
  "Oberkampf": ["5", "9"],
  "Louis Blanc": ["7", "7bis"],
  "Trocadéro": ["6", "9"],
  "La Motte-Picquet–Grenelle": ["6", "8", "10"],
  "Pasteur": ["6", "12"],
  "Bercy": ["6", "14"],
  "Daumesnil": ["6", "8"],
  "Chaussée d'Antin–La Fayette": ["7", "9"],
  "Jussieu": ["7", "10"],
  "Maison Blanche": ["7", "14"],
  "Madeleine": ["8", "12", "14"],
  "Invalides": ["8", "13"],
  "Richelieu–Drouot": ["8", "9"],
  "Grands Boulevards": ["8", "9"],
  "Bonne Nouvelle": ["8", "9"],
  "Sèvres–Babylone": ["10", "12"],
  "Duroc": ["10", "13"],
  "Place des Fêtes": ["7bis", "11"],
  "Miromesnil": ["9", "13"],
  "Porte de Clichy": ["13", "14"],
  "Saint-Ouen": ["13", "14"]
};

/* Landmarks -> [english, french, station, headline line] */
const LANDMARKS = [
  ["the Eiffel Tower", "la tour Eiffel", "Bir-Hakeim", "6"],
  ["the Arc de Triomphe", "l'Arc de Triomphe", "Charles de Gaulle–Étoile", "1"],
  ["the Louvre", "le Louvre", "Palais Royal–Musée du Louvre", "1"],
  ["Notre-Dame de Paris", "Notre-Dame de Paris", "Cité", "4"],
  ["the Sainte-Chapelle", "la Sainte-Chapelle", "Cité", "4"],
  ["the Sacré-Cœur basilica", "la basilique du Sacré-Cœur", "Anvers", "2"],
  ["the Moulin Rouge", "le Moulin Rouge", "Blanche", "2"],
  ["the Opéra Garnier", "l'Opéra Garnier", "Opéra", "3"],
  ["the Musée d'Orsay", "le musée d'Orsay", "Solférino", "12"],
  ["the Centre Pompidou", "le Centre Pompidou", "Rambuteau", "11"],
  ["the Catacombs of Paris", "les Catacombes de Paris", "Denfert-Rochereau", "6"],
  ["the Panthéon", "le Panthéon", "Cardinal Lemoine", "10"],
  ["the Musée Rodin", "le musée Rodin", "Varenne", "13"],
  ["the Grand Palais", "le Grand Palais", "Champs-Élysées–Clemenceau", "13"],
  ["the Palais de Tokyo", "le palais de Tokyo", "Iéna", "9"],
  ["Les Invalides / Napoleon's tomb", "les Invalides et le tombeau de Napoléon", "Invalides", "8"],
  ["the Parc des Buttes-Chaumont", "le parc des Buttes-Chaumont", "Buttes Chaumont", "7bis"],
  ["the Cité des Sciences at La Villette", "la Cité des sciences, à La Villette", "Porte de la Villette", "7"],
  ["the Philharmonie de Paris", "la Philharmonie de Paris", "Porte de Pantin", "5"],
  ["the Jardin des Plantes", "le Jardin des Plantes", "Jussieu", "7"],
  ["the Grande Mosquée de Paris", "la Grande Mosquée de Paris", "Place Monge", "7"],
  ["Bercy Village", "Bercy Village", "Cour Saint-Émilion", "14"],
  ["the Bibliothèque nationale (site François-Mitterrand)", "la BnF, site François-Mitterrand", "Bibliothèque François Mitterrand", "14"],
  ["Orly airport", "l'aéroport d'Orly", "Aéroport d'Orly", "14"],
  ["the Grande Arche de la Défense", "la Grande Arche de la Défense", "La Défense", "1"],
  ["the Château de Vincennes", "le château de Vincennes", "Château de Vincennes", "1"],
  ["the Paris zoo (Parc zoologique)", "le Parc zoologique de Paris", "Porte Dorée", "8"],
  ["the Parc des Princes", "le Parc des Princes", "Porte de Saint-Cloud", "9"],
  ["Roland-Garros", "Roland-Garros", "Porte d'Auteuil", "10"],
  ["the Basilica of Saint-Denis", "la basilique de Saint-Denis", "Basilique de Saint-Denis", "13"],
  ["the Galeries Lafayette", "les Galeries Lafayette", "Chaussée d'Antin–La Fayette", "7"],
  ["the Musée Grévin", "le musée Grévin", "Grands Boulevards", "8"],
  ["Père Lachaise cemetery", "le cimetière du Père-Lachaise", "Père Lachaise", "2"],
  ["the Musée Picasso in the Marais", "le musée Picasso, dans le Marais", "Saint-Sébastien–Froissart", "8"],
  ["the Tour Montparnasse", "la tour Montparnasse", "Montparnasse–Bienvenüe", "6"],
  ["the Paris expo at Porte de Versailles", "le parc des expositions de la porte de Versailles", "Porte de Versailles", "12"],
  ["Place de la Concorde and its obelisk", "la place de la Concorde et son obélisque", "Concorde", "1"],
  ["the Canal Saint-Martin", "le canal Saint-Martin", "Jacques Bonsergent", "5"],
  ["the Bois de Boulogne (north entrance)", "le bois de Boulogne (entrée nord)", "Porte Dauphine", "2"],
  ["the Champs-Élysées, halfway up", "les Champs-Élysées, à mi-parcours", "George V", "1"]
];
